### PR TITLE
populate travis.yml

### PR DESCRIPTION
**Pull request by tkelman**
needs to be enabled

### CODE REVIEW

**Comment by andyreagan** [comment]
awesome, thanks!!

**Comment by tkelman** [comment]
you'll need to manually turn it on at travis-ci.org. Helps to add a status badge to the readme after you do.

**Comment by andyreagan** [comment]
both done. thanks for the help!!

next: I need to get tests to pass in 0.4

**Comment by tkelman** [comment]
The Compat.jl package will likely be useful for maintaining compatibility across multiple versions of Julia.

**Comment by andyreagan** [comment]
great! will investigate.

**Pull request merged**
